# -*- encoding: utf-8 -*-

{
    "name": "Pdf Print Preview",
    "version": "1.0",
    "depends": ["web"],
    "author": "itechgroup",
    "category": "web",
    "website": "",
    "summary": "Preview and print PDF report in your browser",
    "description": """
        Preview,
        Preview PDF,
        Preview print PDF,
        Preview report,
        Report,
        Print,
        Pdf direct preview,
        PDF preview,
        Direct preview,
        Direct print,
        Print Without Download,
        Print without,
        Download,
        Without Download,
        Quick Printer,
        Printer,
        Quick Pdf,
        Pos report,
        Pos,
        Sale,
        Purchase,
        Stock,
        Print report,
        Easily to print report,
        Without download PDF File,
        Preview without Download,
        doo Dashboard, 
        Dashboard,
        Odoo apps,
        Dashboard app,
        HR Dashboard,
        Sales Dashboard, 
        inventory Dashboard, 
        Lead Dashboard, 
        Opportunity Dashboard, 
        CRM Dashboard,
	    POS,
	    POS Dashboard,
        Dashboard Manager,
	    Report Import/Export,
        Dashboard Widgets,
	    Dashboard Manager,
	    Web Dynamic,
	    Report Import/Export,
	    Date Filter,
	    HR,
	    Sales,
	    Report Import/Export,
	    Theme,
        Customize Dashboard,
	    Tile Dashboard,
	    Dashboard Widgets,
        Theme,
	    Project management,
        List View Manager,
	    Dashboard Manager,
	    Debranding,
        Connectors,
	    Customize Dashboard,
        Dashboard Ninja,
        Odoo WooCommerce Connector,
	    Graph Dashboard,
	    Charts Dashboard,
	    Invoice Dashboard,
        Sales,
        Graph Dashboard,
	    Theme,
	    Project management,
        Dashboard Ninja,
        Odoo WooCommerce Connector,
        Gantt Native Web view
    """,
    "live_test_url": "https://www.youtube.com/watch?v=hEXqt4moKts",
    "data": [
        "views/assets.xml",
        "views/res_users.xml"
    ],
    "qweb": [
        "static/src/xml/*.xml"
    ],
    "images": [ "static/description/banner.png" ],
    "installable": True,
    "application": True,
    "currency": "EUR",
    "price": 25.99
}
