version: 0.2

env:
    variables:
        VERSION: "8.0"
        TESTS: "0"
        LINT_CHECK: "1"
        TRANSIFEX: "0"
phases:
    install:
        commands:
            - sudo apt-get update
            - sudo apt-get -y upgrade
            - sudo apt-get -y install expect-dev python-lxml python-simplejson python-serial python-yaml
